# BEST TMUXRC YOU WOULD COME ACROSS YOU KNOW WHAT I MEAN?
#
# Author: Eri A.
# Updated: 2026-02-15

source-file ~/.config/tmux/.tmux.bindings.conf
set -g default-terminal 'tmux-256color'
set -g terminal-overrides ',xterm-256color:RGB'

set -g prefix C-a
unbind C-b
unbind -n M-h

set -g mouse on
set -g detach-on-destroy off
set -g escape-time 0     # reduce time overhead time between commmands
set -g base-index 1      # switch to 1-based indexing, zero-based makes no sense
setw -g pane-base-index 1   # switch to 1-based indexing for panes as well
set -g renumber-windows on  # renumber windows when one is closed
set -g set-clipboard on     # use the system clipboard
bind-key C-a send-prefix    # Bind C-a to send a tmux command
set -g history-limit 100000   # increase scrollback buffer size
setw -g mode-keys vi     # use vi keys in copy mode

# we don't love our green damn colour, give us a blue over brown bg
set -g status-style 'bg=#333333 fg=#5eacd3'

# navigate tmux panes with vim keys 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm' 
